
name = "DashCoolComponents"
uuid = "1b08a953-4be3-4667-9a23-551e061d85af"
authors = ["Luiz Tauffer and Vinicius Camozzato Vaz <vinicvaz.dev@gmail.com>"]
version = "0.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compact]
julia = "1.2"
Dash = ">=0.1"
